#%RAML 1.0 Library
usage: we create case object, a case object has source, case type, firstname,lastname, date of birth, phone ,email(optional),nationalId, nationalIdtype,address, address internally will have street, city,pincode, state and country

types:
  case:
    type: object
    properties:
      source:
        type: string
        maxLength: 60
        minLength: 1
        required: true
      caseType:
        required: true
        type: 
          enum:
            - positive
            - recovered
            - death
            - vaccinated
      firstName:
        type: string
        maxLength: 20
        minLength: 1
        required: true
      lastName: 
        type: string
        maxLength: 20
        minLength: 1
        required: true
      dateOfBirth:
        type: date-only
        required: true
      phone:
        type: string
        required: true
        minLength: 1
        maxLength: 12  
      email:
        type: string
        required: false
        minLength: 1
        maxLength: 50 
      nationalID:
        type: string
        required: true
        minLength: 1
        maxLength: 20
      nationalIDType:
        type: string
        required: true
        minLength: 1
        maxLength: 20
      address:
        type: object
        properties:
          streetAddress:
            type: string
            required: true
            minLength: 1
            maxLength: 60
          city:
            type: string
            required: true
            minLength: 1
            maxLength: 20
          postal:
            type: string
            required: true
            minLength: 1
            maxLength: 20
          state:
            type: string
            required: true
            minLength: 1
            maxLength: 30
          country:
            type: string
            required: true
            minLength: 1
            maxLength: 30
  case_response:
    type: object
    properties:
      caseID:
        type: string
