{
  "headers": {
    "client-id": "asdreasfsd",
    "client-secret": "asdfaffasf",
    "x-transaction-id": "dasdasd",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.28.4",
    "accept": "*/*",
    "postman-token": "d59d1223-6d4a-45d3-931d-dfeb9c3c8485",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "451"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/reports",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/reports",
  "listenerPath": "/api/*",
  "relativePath": "/api/reports",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/reports",
  "rawRequestPath": "/api/reports",
  "remoteAddress": "/127.0.0.1:64152",
  "requestPath": "/api/reports"
}