{
  "headers": {
    "client-id": "asdreasfsd",
    "client-secret": "asdfaffasf",
    "x-transaction-id": "dasdasd",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.28.4",
    "accept": "*/*",
    "postman-token": "2cc5cd2a-1c24-4bdd-8fdc-433033aef340",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "449"
  },
  "clientCertificate": null,
  "method": "PUT",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/cases",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/cases",
  "listenerPath": "/api/*",
  "relativePath": "/api/cases",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/cases",
  "rawRequestPath": "/api/cases",
  "remoteAddress": "/127.0.0.1:64521",
  "requestPath": "/api/cases"
}